# -*- coding: utf-8 -*-
"""5-dia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBSqh0QrT_kMBh-c9wNBmRSHj_etiCs1
"""

import pandas as pd

df = pd.read_csv('/content/dados_nao_tratados.csv')
display(df)

df["idade"] = pd.to_numeric(df["idade"], errors='coerce')
df["idade"] = df["idade"].astype('Int64')
display(df)

df['data_inscricao'] = pd.to_datetime(df['data_inscricao'], errors='coerce')
display(df)

df["nota"] = pd.to_numeric(df["nota"], errors='coerce')
df["nota"] = df["nota"].astype('Float64')
display(df)

df["ativo"] = df["ativo"].fillna('').str.strip().str.lower().map({'sim': True, 'true': True, 'yes': True, 'não': False, 'false': False, 'nao': False})
display(df)

df['idade'] = df['idade'].fillna(1)
display(df)

df['nota'] = df['nota'].fillna(1.1)
display(df)

df['data_inscricao'] = df['data_inscricao'].fillna(9)
display(df)

df['ativo'] = df['ativo'].fillna('Sem dados')
display(df)

df.to_csv("dados_tratados.csv", index=False)

from google.colab import files
files.download("dados_tratados.csv")